### ISSUE TITLE
Deleting a Character from the Battlefield

### ISSUE THREAD

**Issue by seball** [seball/5e-encounter#2]
**As a user**, I want to be able to delete a created character (monster or player) from the battlefield so that I can manage the current state of the battle without irrelevant or defeated characters cluttering the display.

#### Acceptance Criteria:
- A delete option should be available for each character (monster or player) currently displayed on the battlefield.
- Deleting a character should remove it visually from the battlefield component.
- The character's stats and information should no longer be available or accessible from any other components (e.g., statblock) after deletion.
- Confirmation prompt before deleting a character to avoid accidental removal.
- Deletion should update the state across the entire application to ensure that the character is fully removed.

**Comment by mcw256** [comment]
@seball @dawid512 

I pushed work in progress commit to this branch. Several things need to be dertermined before we can continue with this.

1. There is no ID field in Character, so when deleting character I temporary passed name (that however creates a bug when there are more characters with same name all of them gets deleted)

Decide whether we want to have ID field in character!

2. I temporarily used javascript confirm function to show confirmation dialog, because showing dialogs with just a bootstrap is not so straightforward and elegant like it was with angular material which we don't have 

3. I temporarily made Delete button to look like so:
![image](https://github.com/user-attachments/assets/b482921c-5406-4774-890c-9a5ade9bb8a9)

Decide where you want this button to be and how it should look (maybe some trash can icon?)! 

You can make changes on this branch.

**Comment by seball** [comment]
dont worry about delete button, i will use context menu for it. Adding Id is a good idea, add incremental value from 0 to n or u think guid will be better? not sure
